name: Django CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
  
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint and format
      hooks:
      run: |
        pip install --upgrade click==8.0.2
        black --check src 
        flake8 src

